FROM eboraas/apache-php
MAINTAINER zhanglindeng <zhanglindeng@163.com>

RUN apt-get update && apt-get -y install php5-curl php5-gd && apt-get clean && rm -rf /var/lib/apt/lists/*
RUN a2enmod rewrite

WORKDIR /var/www/html

EXPOSE 80
EXPOSE 443

CMD ["/usr/sbin/apache2ctl", "-D", "FOREGROUND"]
